import { prisma } from "@/lib/prisma";
import { notFound } from "next/navigation";
import Link from "next/link";
import { format } from "date-fns";

interface BlogPostPageProps {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({ params }: BlogPostPageProps) {
  const { slug } = await params;
  const post = await prisma.post.findUnique({
    where: { slug, status: "published" },
    select: { title: true, summary: true },
  });

  if (!post) return { title: "Post Not Found" };

  return {
    title: post.title,
    description: post.summary,
  };
}

export default async function BlogPostPage({ params }: BlogPostPageProps) {
  const { slug } = await params;
  const post = await prisma.post.findUnique({
    where: { slug, status: "published" },
  });

  if (!post) {
    notFound();
  }

  // Simple Markdown-to-HTML: handle headings, bold, italic, lists, links, code blocks
  const renderMarkdown = (content: string) => {
    const lines = content.split("\n");
    const htmlLines: string[] = [];
    let inCodeBlock = false;

    for (const line of lines) {
      if (line.startsWith("```")) {
        inCodeBlock = !inCodeBlock;
        htmlLines.push(
          inCodeBlock
            ? '<pre class="bg-gray-900 text-gray-100 p-4 rounded-xl overflow-x-auto my-4"><code>'
            : "</code></pre>",
        );
        continue;
      }

      if (inCodeBlock) {
        htmlLines.push(line.replace(/</g, "&lt;").replace(/>/g, "&gt;") + "\n");
        continue;
      }

      let processed = line;

      // Headings
      if (processed.startsWith("### ")) {
        processed = `<h3 class="text-xl font-bold text-gray-900 mt-8 mb-3">${processed.slice(4)}</h3>`;
      } else if (processed.startsWith("## ")) {
        processed = `<h2 class="text-2xl font-bold text-gray-900 mt-10 mb-4">${processed.slice(3)}</h2>`;
      } else if (processed.startsWith("# ")) {
        processed = `<h1 class="text-3xl font-bold text-gray-900 mt-10 mb-4">${processed.slice(2)}</h1>`;
      } else if (processed.startsWith("- ") || processed.startsWith("* ")) {
        processed = `<li class="ml-6 list-disc text-gray-700 leading-relaxed">${processed.slice(2)}</li>`;
      } else if (/^\d+\.\s/.test(processed)) {
        processed = `<li class="ml-6 list-decimal text-gray-700 leading-relaxed">${processed.replace(/^\d+\.\s/, "")}</li>`;
      } else if (processed.trim() === "") {
        processed = '<div class="h-4"></div>';
      } else {
        processed = `<p class="text-gray-700 leading-relaxed mb-4">${processed}</p>`;
      }

      // Inline formatting
      processed = processed
        .replace(/\*\*(.+?)\*\*/g, '<strong class="font-semibold">$1</strong>')
        .replace(/\*(.+?)\*/g, "<em>$1</em>")
        .replace(
          /`(.+?)`/g,
          '<code class="bg-gray-100 px-1.5 py-0.5 rounded text-sm text-pink-600">$1</code>',
        )
        .replace(
          /\[(.+?)\]\((.+?)\)/g,
          '<a href="$2" class="text-blue-600 hover:underline" target="_blank" rel="noopener noreferrer">$1</a>',
        );

      htmlLines.push(processed);
    }

    return htmlLines.join("\n");
  };

  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <Link
        href="/"
        className="inline-flex items-center text-sm text-gray-500 hover:text-gray-700 mb-8 transition-colors"
      >
        ← Back to Blog
      </Link>

      <article>
        <header className="mb-8">
          <div className="flex items-center gap-2 mb-4">
            <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
              {post.topic}
            </span>
            {post.publishedAt && (
              <time className="text-sm text-gray-400">
                {format(new Date(post.publishedAt), "MMMM d, yyyy")}
              </time>
            )}
          </div>
          <h1 className="text-4xl font-bold text-gray-900 leading-tight">
            {post.title}
          </h1>
          <p className="text-lg text-gray-500 mt-4">{post.summary}</p>
        </header>

        <div
          className="prose prose-lg max-w-none"
          dangerouslySetInnerHTML={{ __html: renderMarkdown(post.content) }}
        />
      </article>

      <div className="mt-12 pt-8 border-t border-gray-200">
        <p className="text-sm text-gray-400 text-center">
          This post was generated by AI based on web research about &ldquo;
          {post.topic}&rdquo;
        </p>
      </div>
    </div>
  );
}
